### ISSUE TITLE
Simplify IDs on <p> tags

### ISSUE THREAD

**Issue by acabal** [davgross/william-wollaston-the-religion-of-nature-delineated#12]
It's common to need to put IDs on &lt;p&gt; tags, so that we can link notes to them.  But a quick glance suggests the IDs should be simplified.  Generally we just use a scheme like &lt;p id="p-12"&gt;.  Looking at section-5.xhtml I see one called &lt;p id="s5p19n3"&gt; and another called &lt;p id="v1"&gt;.  Can we simplify those to match our existing scheme?

See https://github.com/standardebooks/marcus-aurelius_meditations_george-long for a live example

**Comment by davgross** [comment]
s5p19n3 denotes "section 5, proposition 19, number 3" in Wollaston's somewhat baroque numbering scheme. That more complicated syntax made it easier for me to know which id I was referring to, while just using the number of the paragraph would have been more opaque (and would have made me have to go through and count paragraphs... When I put IDs on paragraphs, rather than on notes, this was usually to support internal hyperlinks: in this case, where, in section 8, Wollaston writes "(according to Section V, proposition XIX, no. 3)".

**Comment by acabal** [comment]
I figured, but consistency is key across all of these books.  A lot of our books already use the id="p-#" scheme, so if we're hooking to a whole paragraph we should just stick to that scheme.
